# question 5

In [18]:
import numpy as np

In [19]:
import matplotlib.pyplot as plt

In [20]:
import seaborn as sns

In [21]:
from numpy import random

In [22]:
matrix=np.array([[1,0.2,0.5], [0.2,1,0.8], [0.5,0.8,1]])
print(matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


# (i)

In [23]:
matrix_transpose= np.transpose(matrix)
print(matrix_transpose)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


# (ii)

In [ ]:
poisson_data=random.poisson( size=10)
sns.kdeplot(poisson_data, color="green")
plt.xlabel("Number of success")
plt.ylabel("Frequency")
plt.title("Visualization of Poisson Distribution")
plt.show()
x=random.poisson(lam=2,size=10)#lam is number of occurance
print(x)